server:
  port: 8081
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    pool:
      max-active: 10
      max-idle: 5
      max-wait: -1
      min-idle: 0
    timeout: 0