server:
  port: 8098
spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    suffix: .html
    prefix:  classpath:/template/
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/aididi-security?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name:  com.mysql.jdbc.Driver
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #¿ªÆôÍÕ·åÃüÃû·¨